version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    build: .
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/workspace:/workspace
      - /docker/machines:/machines
      - /docker/jenkins:/var/jenkins_home
    environment:
      JENKINS_OPTS: --prefix=/jenkins

