version: '3.3'
services:
  jenkins:
    image: ${swarm_manager_ip}:5000/jenkins
    build: .
    ports:
      - '8080:8080'
      - '50000:50000'
    dns:
      - ${dns1}
      - ${dns2}
    dns_search:
      - ${search_domain}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${workspace_dir}:/workspace
      - ${machines_dir}:/machines
      - ${jenkins_dir}:/var/jenkins_home
    environment:
      JENKINS_OPTS: --prefix=/jenkins
